### ISSUE TITLE
Autocomplete Icons

### ISSUE THREAD

**Issue by AstroLuluGit** [RyonicFire/Dotfiles#4]
Currently we are using a Hack Font which doesn't render icons correctly. We could use a Hack Nerdfont which would resolve this problem.

![grafik](https://user-images.githubusercontent.com/43894665/193041603-bb56a5c0-8720-42b6-9736-9831aa01563b.png)

**Comment by RyonicFire** [comment]
I can disable icons or change the install script to install yay and the nerd-fonts-hack repository from the AUR. What do you prefer?

**Comment by AstroLuluGit** [comment]
What about downloading a nerdfont package for hack from somewhere with like
wget, and installing it manually in the install script, so we don't have
the problem with yay?

Kevin Danne ***@***.***> schrieb am Sa., 15. Okt. 2022, 13:29:

**Comment by RyonicFire** [comment]
Fixed since 55ec242900b846ca772768e4fbff01266d0b5af4
