### ISSUE TITLE
Discussion: New Theme

### ISSUE THREAD

**Issue by AstroLuluGit** [RyonicFire/Dotfiles#5]
We are thinking of removing Gruvbox and switching to another theme. We already compared multiple Themes [Here](https://drive.google.com/drive/folders/1RlKN5HnBNvaw0bRf0JCdlALtgoj2M-zl?usp=sharing).

**Comment by RyonicFire** [comment]
Beta branch is now using monokai for neovim. The Kitty theme will also be changed soon.
Feedback for monokai is welcome.

**Comment by AstroLuluGit** [comment]
Hello! I tried the new monokai.soda theme, and it looks very nice. Much better than gruvbox. Much nicer colors. I like it very well. 

I am looking forward to the new Kitty theme.

**Comment by AstroLuluGit** [comment]
Here is a comparison of some themes @RyonicFire  and I tried. 

My current order of which i like most is:

Carbonfox > Tokyonight-Night > Monokai_Soda > Gruvbox

Sadly i am currently having issues with my Treesitter "comment" parser, so the comment highlighting is not working correctly. 


Gruvbox:
![gruvbox](https://user-images.githubusercontent.com/43894665/196056604-6c237211-e2f9-4d08-819d-2082b23b27c6.png)
Monokai_Soda:
![monokai_soda](https://user-images.githubusercontent.com/43894665/196056608-51e2e6a0-76bf-44f4-a7ef-903064df6935.png)
Tokyonight-Night:
![tokyonight-night](https://user-images.githubusercontent.com/43894665/196056609-631810e7-954f-4468-afd0-394330c0365b.png)
Carbonfox:
![carbonfox](https://user-images.githubusercontent.com/43894665/196056610-5a936b45-e3ba-419b-99e5-d4992361db62.png)

**Comment by RyonicFire** [comment]
Nightfox looks nice too:
![image](https://user-images.githubusercontent.com/26122654/196122732-0f2c51b2-e00c-4db0-b7c2-926a49bfd16d.png)

**Comment by AstroLuluGit** [comment]
I don't like the background color of normal nightfox

**Comment by RyonicFire** [comment]
Beta branch is now using tokyonight-night for neovim. Thanks for your help comparing themes @AstroLuluGit

**Comment by RyonicFire** [comment]
After talking with @AstroLuluGit  and @R3C0N1Z3R we decided to switch to nightfox with the carbonfox variant. Nvim and kitty configs are changed. Changes are in beta + master branch.

Thanks for your help.
